name: images are public
on:
  push:
    branches:
      - main
jobs:
  images-are-public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      - uses: GeoNet/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # main
      - name: check images are public
        run: |
          # NOTE: important to not use auth
          jq -r -c '.sync as $sync | .build as $build | {"include":[{"destination": $sync[].destination}, {"destination": $build[].destination}]} | .include[] | select(.destination | contains("amazonaws.com") | not) | .destination' <<< "$(yq e . -o json config.yaml)" \
            | xargs -n 1 -I{} crane digest {}
